ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SM_LM0123_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_50 = ', GC_50
      WRITE(*,2) 'GC_56 = ', GC_56
      WRITE(*,2) 'GC_143 = ', GC_143
      WRITE(*,2) 'GC_144 = ', GC_144
