ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' External Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_FS0 = ', MDL_FS0
      WRITE(*,*) 'mdl_FS1 = ', MDL_FS1
      WRITE(*,*) 'mdl_FM0 = ', MDL_FM0
      WRITE(*,*) 'mdl_FM1 = ', MDL_FM1
      WRITE(*,*) 'mdl_FM2 = ', MDL_FM2
      WRITE(*,*) 'mdl_FM3 = ', MDL_FM3
      WRITE(*,*) 'mdl_FM4 = ', MDL_FM4
      WRITE(*,*) 'mdl_FM5 = ', MDL_FM5
      WRITE(*,*) 'mdl_FM6 = ', MDL_FM6
      WRITE(*,*) 'mdl_FM7 = ', MDL_FM7
      WRITE(*,*) 'mdl_FT0 = ', MDL_FT0
      WRITE(*,*) 'mdl_FT1 = ', MDL_FT1
      WRITE(*,*) 'mdl_FT2 = ', MDL_FT2
      WRITE(*,*) 'mdl_FT3 = ', MDL_FT3
      WRITE(*,*) 'mdl_FT4 = ', MDL_FT4
      WRITE(*,*) 'mdl_FT5 = ', MDL_FT5
      WRITE(*,*) 'mdl_FT6 = ', MDL_FT6
      WRITE(*,*) 'mdl_FT7 = ', MDL_FT7
      WRITE(*,*) 'mdl_FT8 = ', MDL_FT8
      WRITE(*,*) 'mdl_FT9 = ', MDL_FT9
      WRITE(*,*) 'mdl_cabi = ', MDL_CABI
      WRITE(*,*) 'aEWM1 = ', AEWM1
      WRITE(*,*) 'mdl_Gf = ', MDL_GF
      WRITE(*,*) 'aS = ', AS
      WRITE(*,*) 'mdl_ymb = ', MDL_YMB
      WRITE(*,*) 'mdl_ymt = ', MDL_YMT
      WRITE(*,*) 'mdl_ymtau = ', MDL_YMTAU
      WRITE(*,*) 'mdl_MTA = ', MDL_MTA
      WRITE(*,*) 'mdl_MT = ', MDL_MT
      WRITE(*,*) 'mdl_MB = ', MDL_MB
      WRITE(*,*) 'mdl_MZ = ', MDL_MZ
      WRITE(*,*) 'mdl_MH = ', MDL_MH
      WRITE(*,*) 'mdl_WT = ', MDL_WT
      WRITE(*,*) 'mdl_WZ = ', MDL_WZ
      WRITE(*,*) 'mdl_WW = ', MDL_WW
      WRITE(*,*) 'mdl_WH = ', MDL_WH
      WRITE(*,*)  ' Internal Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_cos__cabi = ', MDL_COS__CABI
      WRITE(*,*) 'mdl_CKM11 = ', MDL_CKM11
      WRITE(*,*) 'mdl_sin__cabi = ', MDL_SIN__CABI
      WRITE(*,*) 'mdl_CKM12 = ', MDL_CKM12
      WRITE(*,*) 'mdl_CKM21 = ', MDL_CKM21
      WRITE(*,*) 'mdl_CKM22 = ', MDL_CKM22
      WRITE(*,*) 'mdl_MZ__exp__2 = ', MDL_MZ__EXP__2
      WRITE(*,*) 'mdl_MZ__exp__4 = ', MDL_MZ__EXP__4
      WRITE(*,*) 'mdl_sqrt__2 = ', MDL_SQRT__2
      WRITE(*,*) 'mdl_MH__exp__2 = ', MDL_MH__EXP__2
      WRITE(*,*) 'mdl_complexi = ', MDL_COMPLEXI
      WRITE(*,*) 'mdl_conjg__CKM11 = ', MDL_CONJG__CKM11
      WRITE(*,*) 'mdl_conjg__CKM12 = ', MDL_CONJG__CKM12
      WRITE(*,*) 'mdl_conjg__CKM21 = ', MDL_CONJG__CKM21
      WRITE(*,*) 'mdl_conjg__CKM22 = ', MDL_CONJG__CKM22
      WRITE(*,*) 'mdl_aEW = ', MDL_AEW
      WRITE(*,*) 'mdl_MW = ', MDL_MW
      WRITE(*,*) 'mdl_sqrt__aEW = ', MDL_SQRT__AEW
      WRITE(*,*) 'mdl_ee = ', MDL_EE
      WRITE(*,*) 'mdl_MW__exp__2 = ', MDL_MW__EXP__2
      WRITE(*,*) 'mdl_sw2 = ', MDL_SW2
      WRITE(*,*) 'mdl_cw = ', MDL_CW
      WRITE(*,*) 'mdl_sqrt__sw2 = ', MDL_SQRT__SW2
      WRITE(*,*) 'mdl_sw = ', MDL_SW
      WRITE(*,*) 'mdl_g1 = ', MDL_G1
      WRITE(*,*) 'mdl_gw = ', MDL_GW
      WRITE(*,*) 'mdl_v = ', MDL_V
      WRITE(*,*) 'mdl_v__exp__2 = ', MDL_V__EXP__2
      WRITE(*,*) 'mdl_lam = ', MDL_LAM
      WRITE(*,*) 'mdl_yb = ', MDL_YB
      WRITE(*,*) 'mdl_yt = ', MDL_YT
      WRITE(*,*) 'mdl_ytau = ', MDL_YTAU
      WRITE(*,*) 'mdl_muH = ', MDL_MUH
      WRITE(*,*) 'mdl_ee__exp__2 = ', MDL_EE__EXP__2
      WRITE(*,*) 'mdl_gw__exp__2 = ', MDL_GW__EXP__2
      WRITE(*,*) 'mdl_cw__exp__2 = ', MDL_CW__EXP__2
      WRITE(*,*) 'mdl_sw__exp__2 = ', MDL_SW__EXP__2
      WRITE(*,*) 'mdl_cw__exp__3 = ', MDL_CW__EXP__3
      WRITE(*,*) 'mdl_cw__exp__4 = ', MDL_CW__EXP__4
      WRITE(*,*) 'mdl_sw__exp__3 = ', MDL_SW__EXP__3
      WRITE(*,*) 'mdl_sw__exp__4 = ', MDL_SW__EXP__4
      WRITE(*,*)  ' Internal Params evaluated point by point'
      WRITE(*,*)  ' ----------------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_sqrt__aS = ', MDL_SQRT__AS
      WRITE(*,*) 'mdl_G__exp__2 = ', MDL_G__EXP__2
