C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(1,2)*P(2,1)*Metric(3,4) -
C      P(-1,1)*P(-1,2)*Metric(1,2)*Metric(3,4)
C     
      SUBROUTINE VVVV11P1N_2(V1, V3, V4, COUP,V2)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      REAL*8 P1(0:3)
      REAL*8 P2(0:3)
      COMPLEX*16 TMP12
      COMPLEX*16 TMP7
      COMPLEX*16 TMP9
      COMPLEX*16 V1(*)
      COMPLEX*16 V2(6)
      COMPLEX*16 V3(*)
      COMPLEX*16 V4(*)
      P1(0) = DBLE(V1(1))
      P1(1) = DBLE(V1(2))
      P1(2) = DIMAG(V1(2))
      P1(3) = DIMAG(V1(1))
      V2(1) = +V1(1)+V3(1)+V4(1)
      V2(2) = +V1(2)+V3(2)+V4(2)
      P2(0) = -DBLE(V2(1))
      P2(1) = -DBLE(V2(2))
      P2(2) = -DIMAG(V2(2))
      P2(3) = -DIMAG(V2(1))
      TMP12 = (V3(3)*V4(3)-V3(4)*V4(4)-V3(5)*V4(5)-V3(6)*V4(6))
      TMP7 = (V1(3)*P2(0)-V1(4)*P2(1)-V1(5)*P2(2)-V1(6)*P2(3))
      TMP9 = (P1(0)*P2(0)-P1(1)*P2(1)-P1(2)*P2(2)-P1(3)*P2(3))
      V2(3)= COUP*TMP12*(-CI*(P1(0)*TMP7)+CI*(V1(3)*TMP9))
      V2(4)= COUP*TMP12*(+CI*(P1(1)*TMP7)-CI*(V1(4)*TMP9))
      V2(5)= COUP*TMP12*(+CI*(P1(2)*TMP7)-CI*(V1(5)*TMP9))
      V2(6)= COUP*TMP12*(+CI*(P1(3)*TMP7)-CI*(V1(6)*TMP9))
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(1,2)*P(2,1)*Metric(3,4) -
C      P(-1,1)*P(-1,2)*Metric(1,2)*Metric(3,4)
C     
      SUBROUTINE VVVV11_3P1N_2(V1, V3, V4, COUP1, COUP2,V2)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      REAL*8 P1(0:3)
      REAL*8 P2(0:3)
      COMPLEX*16 V1(*)
      COMPLEX*16 V2(6)
      COMPLEX*16 V3(*)
      COMPLEX*16 V4(*)
      COMPLEX*16 VTMP(6)
      INTEGER*4 I
      CALL VVVV11P1N_2(V1,V3,V4,COUP1,V2)
      CALL VVVV3P1N_2(V1,V3,V4,COUP2,VTMP)
      DO I = 3, 6
        V2(I) = V2(I) + VTMP(I)
      ENDDO
      END


