C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(3,2)*P(4,1)*Metric(1,2) + P(3,1)*P(4,2)*Metric(1,2) -
C      P(2,1)*P(4,2)*Metric(1,3) - P(2,1)*P(3,2)*Metric(1,4) -
C      P(1,2)*P(4,1)*Metric(2,3) +
C      P(-1,1)*P(-1,2)*Metric(1,4)*Metric(2,3) -
C      P(1,2)*P(3,1)*Metric(2,4) +
C      P(-1,1)*P(-1,2)*Metric(1,3)*Metric(2,4)
C     
      SUBROUTINE VVVV3P1N_3(V1, V2, V4, COUP,V3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      REAL*8 P1(0:3)
      REAL*8 P2(0:3)
      COMPLEX*16 TMP1
      COMPLEX*16 TMP13
      COMPLEX*16 TMP14
      COMPLEX*16 TMP15
      COMPLEX*16 TMP16
      COMPLEX*16 TMP4
      COMPLEX*16 TMP7
      COMPLEX*16 TMP9
      COMPLEX*16 V1(*)
      COMPLEX*16 V2(*)
      COMPLEX*16 V3(6)
      COMPLEX*16 V4(*)
      P1(0) = DBLE(V1(1))
      P1(1) = DBLE(V1(2))
      P1(2) = DIMAG(V1(2))
      P1(3) = DIMAG(V1(1))
      P2(0) = DBLE(V2(1))
      P2(1) = DBLE(V2(2))
      P2(2) = DIMAG(V2(2))
      P2(3) = DIMAG(V2(1))
      TMP1 = (V2(3)*V1(3)-V2(4)*V1(4)-V2(5)*V1(5)-V2(6)*V1(6))
      TMP13 = (P1(0)*V4(3)-P1(1)*V4(4)-P1(2)*V4(5)-P1(3)*V4(6))
      TMP14 = (P2(0)*V4(3)-P2(1)*V4(4)-P2(2)*V4(5)-P2(3)*V4(6))
      TMP15 = (V1(3)*V4(3)-V1(4)*V4(4)-V1(5)*V4(5)-V1(6)*V4(6))
      TMP16 = (V2(3)*V4(3)-V2(4)*V4(4)-V2(5)*V4(5)-V2(6)*V4(6))
      TMP4 = (P1(0)*V2(3)-P1(1)*V2(4)-P1(2)*V2(5)-P1(3)*V2(6))
      TMP7 = (V1(3)*P2(0)-V1(4)*P2(1)-V1(5)*P2(2)-V1(6)*P2(3))
      TMP9 = (P1(0)*P2(0)-P1(1)*P2(1)-P1(2)*P2(2)-P1(3)*P2(3))
      V3(3)= COUP*(P1(0)*(-CI*(TMP1*TMP14)+CI*(TMP7*TMP16))+(P2(0)*(
     $ -CI*(TMP1*TMP13)+CI*(TMP4*TMP15))+(TMP9*(-1D0)*(+CI*(V2(3)
     $ *TMP15+V1(3)*TMP16))+(+CI*(V1(3)*TMP4*TMP14+V2(3)*TMP7*TMP13))))
     $ )
      V3(4)= COUP*(P1(1)*(+CI*(TMP1*TMP14)-CI*(TMP7*TMP16))+(P2(1)*(
     $ +CI*(TMP1*TMP13)-CI*(TMP4*TMP15))+(TMP9*(+CI*(V2(4)*TMP15+V1(4)
     $ *TMP16))+(-CI*(V1(4)*TMP4*TMP14+V2(4)*TMP7*TMP13)))))
      V3(5)= COUP*(P1(2)*(+CI*(TMP1*TMP14)-CI*(TMP7*TMP16))+(P2(2)*(
     $ +CI*(TMP1*TMP13)-CI*(TMP4*TMP15))+(TMP9*(+CI*(V2(5)*TMP15+V1(5)
     $ *TMP16))+(-CI*(V1(5)*TMP4*TMP14+V2(5)*TMP7*TMP13)))))
      V3(6)= COUP*(P1(3)*(+CI*(TMP1*TMP14)-CI*(TMP7*TMP16))+(P2(3)*(
     $ +CI*(TMP1*TMP13)-CI*(TMP4*TMP15))+(TMP9*(+CI*(V2(6)*TMP15+V1(6)
     $ *TMP16))+(-CI*(V1(6)*TMP4*TMP14+V2(6)*TMP7*TMP13)))))
      END


