C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(3,2)*P(4,1)*Metric(1,2) + P(3,1)*P(4,2)*Metric(1,2) -
C      P(2,1)*P(4,2)*Metric(1,3) - P(2,1)*P(3,2)*Metric(1,4) -
C      P(1,2)*P(4,1)*Metric(2,3) +
C      P(-1,1)*P(-1,2)*Metric(1,4)*Metric(2,3) -
C      P(1,2)*P(3,1)*Metric(2,4) +
C      P(-1,1)*P(-1,2)*Metric(1,3)*Metric(2,4)
C     
      SUBROUTINE VVVV3P1N_4(V1, V2, V3, COUP,V4)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      REAL*8 P1(0:3)
      REAL*8 P2(0:3)
      COMPLEX*16 TMP0
      COMPLEX*16 TMP1
      COMPLEX*16 TMP2
      COMPLEX*16 TMP3
      COMPLEX*16 TMP4
      COMPLEX*16 TMP6
      COMPLEX*16 TMP7
      COMPLEX*16 TMP9
      COMPLEX*16 V1(*)
      COMPLEX*16 V2(*)
      COMPLEX*16 V3(*)
      COMPLEX*16 V4(6)
      P1(0) = DBLE(V1(1))
      P1(1) = DBLE(V1(2))
      P1(2) = DIMAG(V1(2))
      P1(3) = DIMAG(V1(1))
      P2(0) = DBLE(V2(1))
      P2(1) = DBLE(V2(2))
      P2(2) = DIMAG(V2(2))
      P2(3) = DIMAG(V2(1))
      TMP0 = (V3(3)*P1(0)-V3(4)*P1(1)-V3(5)*P1(2)-V3(6)*P1(3))
      TMP1 = (V2(3)*V1(3)-V2(4)*V1(4)-V2(5)*V1(5)-V2(6)*V1(6))
      TMP2 = (V3(3)*P2(0)-V3(4)*P2(1)-V3(5)*P2(2)-V3(6)*P2(3))
      TMP3 = (V3(3)*V1(3)-V3(4)*V1(4)-V3(5)*V1(5)-V3(6)*V1(6))
      TMP4 = (P1(0)*V2(3)-P1(1)*V2(4)-P1(2)*V2(5)-P1(3)*V2(6))
      TMP6 = (V3(3)*V2(3)-V3(4)*V2(4)-V3(5)*V2(5)-V3(6)*V2(6))
      TMP7 = (V1(3)*P2(0)-V1(4)*P2(1)-V1(5)*P2(2)-V1(6)*P2(3))
      TMP9 = (P1(0)*P2(0)-P1(1)*P2(1)-P1(2)*P2(2)-P1(3)*P2(3))
      V4(3)= COUP*(P1(0)*(-CI*(TMP1*TMP2)+CI*(TMP6*TMP7))+(P2(0)*(-CI
     $ *(TMP0*TMP1)+CI*(TMP3*TMP4))+(TMP9*(-1D0)*(+CI*(V1(3)*TMP6+V2(3)
     $ *TMP3))+(+CI*(V1(3)*TMP2*TMP4+V2(3)*TMP0*TMP7)))))
      V4(4)= COUP*(P1(1)*(+CI*(TMP1*TMP2)-CI*(TMP6*TMP7))+(P2(1)*(+CI
     $ *(TMP0*TMP1)-CI*(TMP3*TMP4))+(TMP9*(+CI*(V1(4)*TMP6+V2(4)*TMP3))
     $ +(-CI*(V1(4)*TMP2*TMP4+V2(4)*TMP0*TMP7)))))
      V4(5)= COUP*(P1(2)*(+CI*(TMP1*TMP2)-CI*(TMP6*TMP7))+(P2(2)*(+CI
     $ *(TMP0*TMP1)-CI*(TMP3*TMP4))+(TMP9*(+CI*(V1(5)*TMP6+V2(5)*TMP3))
     $ +(-CI*(V1(5)*TMP2*TMP4+V2(5)*TMP0*TMP7)))))
      V4(6)= COUP*(P1(3)*(+CI*(TMP1*TMP2)-CI*(TMP6*TMP7))+(P2(3)*(+CI
     $ *(TMP0*TMP1)-CI*(TMP3*TMP4))+(TMP9*(+CI*(V1(6)*TMP6+V2(6)*TMP3))
     $ +(-CI*(V1(6)*TMP2*TMP4+V2(6)*TMP0*TMP7)))))
      END


